server:
  # 服务端口号
  port: 8085
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: spring-zuul-foos-resource
  sleuth:
    sampler:
      # 日志数据采样百分比，默认0.1(10%)，这里为了测试设置成了100%，生产环境只需要0.1即可
      probability: 1.0
  zipkin:
    #zipkin server的请求地址
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://eurekaServer:8761/eureka
zuul:
  routes:
    feignGreeting:
      path: /feignGreeting/**
      url: http://consumer:9080/feignGreeting