spring:
  application:
    name: spring-cloud-eureka-client
  sleuth:
    sampler:
      # 日志数据采样百分比，默认0.1(10%)，这里为了测试设置成了100%，生产环境只需要0.1即可
      probability: 1.0
  zipkin:
    #zipkin server的请求地址
    base-url: http://zipkin:9411
server:
  port: 9091
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka